### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by voorjaar** [unjs/jiti#25] opened 2021-03-19 16:24 UTC
Trying to switch to jiti. You are doing a really great job.

but I found this. not a big deal. but I think you should know.

when I run `jiti test/run.ts`:

![Screen Shot 2021-03-20 at 00 10 09](https://user-images.githubusercontent.com/69119532/111811271-d7a07a80-8911-11eb-976a-6d74af272c72.png)

but this actually works `node -r jiti/register test/run.ts`

I have encountered the same problem in ts-node before, maybe it will helpful.

https://github.com/TypeStrong/ts-node/issues/922

### Test project

https://github.com/windicss/windicss

**Comment by pi0** [comment] 2021-03-20 10:45
Hi @voorjaar thanks for your kind words and reporting <3

Actually it is intended behavior. The reason is that jiti smartly switches to native require/import on paths that no esm/ts syntax is  detected for a huge performance gain. In our case it is `jasmine/lib/jasmine.js` => `jasmine/lib/loader.js`. Inside loader it tries to require `reporter.ts` but the `loader.js` is a native nodejs module that cannot do this (you can debug with `JITI_DEBUG=1`. When using register approach, jiti uses [pirates](https://www.npmjs.com/package/pirates) that hooks into native `Module` require that directly checks syntax on each entry (`loader.js` is using an `import()`) 

I'm keeping this open to improve in documentation.

**Comment by pi0** [comment] 2024-09-19 11:11
(closing issue as it is too old and behavior of jiti v2 is different with native ESM adoption)

**Closed by pi0** 2024-09-19 11:11 UTC
